### ISSUE TITLE
limit

### ISSUE THREAD

**Issue by port24** [ErrorxCode/BotTube#1]
The bot will comment on the 10 videos matching your keywords

Hello, can you tell me how to change 10 videos, let's say 100?

**Comment by ErrorxCode** [comment]
Simply, you **can't** for many reasons:- 
- Videos are sorted by date (most recent) so you will not get relevant results above 10 videos.
- Each comment costs 50 units of quota. So you will run out of it if there are many keywords (100/keywords)
- To avoid spamming
