### ISSUE TITLE
errors in code prevents from usage

### ISSUE THREAD

**Issue by Raplhs** [ErrorxCode/BotTube#3]
I want to edit this but I get all of these errors when I import the project into my ide:
![errors](https://github.com/ErrorxCode/BotTube/assets/103277643/1980b3fe-c318-499a-bf37-6e8578f8c16d)

I have tried to import the files from your easyyoutube project into this which works but then progressbar doesn't get fixed, I can't fix it properly.

**Comment by ErrorxCode** [comment]
You need to import [this](https://github.com/ErrorxCode/EasyYoutube) as dependency in this project
